# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layergroup', '0006_auto_20160217_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layergroup',
            name='srs',
            field=models.CharField(choices=[(b'EPSG:4326', b'EPSG:4326'), (b'EPSG:3857', b'EPSG:3857')], max_length=320),
        ),
    ]
