# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemanager', '0032_auto_20160615_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='last_modify_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='foreigntable',
            name='last_modify_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='last_modify_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='normalise',
            name='last_modify_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='normaltable',
            name='last_modify_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publish',
            name='last_modify_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publishchannel',
            name='last_modify_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='last_modify_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
