# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablemanager', '0033_auto_20160620_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='default_style',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='kmi_abstract',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='kmi_title',
        ),
    ]
