# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemanager', '0035_auto_20160629_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='advanced_options',
            field=models.CharField(blank=True, help_text='Advanced ogr2ogr options', max_length=128, null=True),
        ),
    ]
