# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 02:11
from __future__ import unicode_literals

from django.db import migrations
import tablemanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemanager', '0035_auto_20160629_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigntable',
            name='sql',
            field=tablemanager.models.SQLField(default='CREATE FOREIGN TABLE "{{schema}}"."{{self.name}}" (<columns>) SERVER {{self.server.name}} OPTIONS (schema \'<schema>\', table \'<table>\');'),
        ),
    ]
