# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-13 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemanager', '0037_auto_20170607_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreigntable',
            name='table_md5_support',
            field=models.BooleanField(default=True, help_text='If true, table md5 is used to check whether the data source is up to date.'),
        ),
    ]
