# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20151124_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksyncstatus',
            name='preview_file',
            field=models.FileField(editable=False, null=True, storage=monitor.models.PreviewFileSystemStorage(), upload_to=monitor.models.get_preview_file_name),
        ),
    ]
