# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_tasksyncstatus_preview_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasksyncstatus',
            unique_together=set([('slave_server', 'task_type', 'task_name', 'action')]),
        ),
    ]
