# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 07:37
from __future__ import unicode_literals

import borg_utils.resource_status
import borg_utils.signal_enable
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablemanager', '0033_auto_20160620_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='The name of live layer datasource', max_length=64, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-z_][a-z0-9_]+$'), 'Slug can only start with lowercase letters or underscore, and contain lowercase letters, numbers and underscore', 'invalid')])),
                ('host', models.CharField(max_length=128)),
                ('port', models.PositiveIntegerField(default=5432)),
                ('db_name', models.CharField(help_text='The name of live layer database', max_length=64)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('schema', models.CharField(default='public', max_length=32)),
                ('geoserver_setting', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'New', b'New'), (b'Updated', b'Updated'), (b'Published', b'Published'), (b'CascadePublished', b'CascadePublished'), (b'Unpublished', b'Unpublished'), (b'CascadeUnpublished', b'CascadeUnpublished')], editable=False, max_length=32)),
                ('layers', models.PositiveIntegerField(default=0, editable=False)),
                ('last_refresh_time', models.DateTimeField(editable=False, null=True)),
                ('last_publish_time', models.DateTimeField(editable=False, null=True)),
                ('last_unpublish_time', models.DateTimeField(editable=False, null=True)),
                ('last_modify_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablemanager.Workspace')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model, borg_utils.resource_status.ResourceStatusManagement, borg_utils.signal_enable.SignalEnable),
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(editable=False, max_length=64)),
                ('type', models.CharField(editable=False, max_length=8)),
                ('spatial_type', models.IntegerField(default=1, editable=False)),
                ('sql', models.TextField(editable=False, null=True)),
                ('crs', models.CharField(editable=False, max_length=64, null=True)),
                ('bbox', models.CharField(editable=False, max_length=128, null=True)),
                ('title', models.CharField(max_length=512, null=True)),
                ('abstract', models.TextField(null=True)),
                ('geoserver_setting', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'New', b'New'), (b'Updated', b'Updated'), (b'Published', b'Published'), (b'CascadePublished', b'CascadePublished'), (b'Unpublished', b'Unpublished'), (b'CascadeUnpublished', b'CascadeUnpublished')], editable=False, max_length=32)),
                ('last_publish_time', models.DateTimeField(editable=False, null=True)),
                ('last_unpublish_time', models.DateTimeField(editable=False, null=True)),
                ('last_refresh_time', models.DateTimeField(editable=False)),
                ('last_modify_time', models.DateTimeField(editable=False, null=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livelayermanager.Datasource')),
            ],
            options={
                'ordering': ('datasource', 'name'),
            },
            bases=(models.Model, borg_utils.resource_status.ResourceStatusManagement, borg_utils.signal_enable.SignalEnable),
        ),
        migrations.CreateModel(
            name='PublishedLayer',
            fields=[
            ],
            options={
                'verbose_name': 'Live layer',
                'proxy': True,
                'verbose_name_plural': 'Live layers',
            },
            bases=('livelayermanager.layer',),
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together=set([('datasource', 'name')]),
        ),
    ]
