# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livelayermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='crs',
            field=models.CharField(default='EPSG:4326', editable=False, max_length=64),
        ),
    ]
