# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livelayermanager', '0002_auto_20160627_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='crs',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
