# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livelayermanager', '0004_datasource_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='crs',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
