# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-20 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livelayermanager', '0006_auto_20160715_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='kmi_bbox',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
