# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 06:59
from __future__ import unicode_literals

import borg_utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livelayermanager', '0008_sqlviewlayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlviewlayer',
            name='status',
            field=models.CharField(choices=[(b'New', b'New'), (b'Updated', b'Updated'), (b'Published', b'Published'), (b'CascadePublished', b'CascadePublished'), (b'Unpublished', b'Unpublished'), (b'CascadeUnpublished', b'CascadeUnpublished')], default=b'New', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='sqlviewlayer',
            name='viewsql',
            field=borg_utils.models.SQLField(),
        ),
    ]
