# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 08:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('livelayermanager', '0009_auto_20170602_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlviewlayer',
            name='name',
            field=models.SlugField(help_text='The name of live layer', max_length=60, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-z_][a-z0-9_]+$'), 'Slug can only start with lowercase letters or underscore, and contain lowercase letters, numbers and underscore', 'invalid')]),
        ),
    ]
