# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-07 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livelayermanager', '0010_auto_20170602_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='bbox',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='crs',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='spatial_type',
        ),
        migrations.RemoveField(
            model_name='sqlviewlayer',
            name='bbox',
        ),
        migrations.RemoveField(
            model_name='sqlviewlayer',
            name='crs',
        ),
        migrations.RemoveField(
            model_name='sqlviewlayer',
            name='spatial_type',
        ),
        migrations.AddField(
            model_name='layer',
            name='spatial_info',
            field=models.TextField(blank=True, editable=False, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='sqlviewlayer',
            name='spatial_info',
            field=models.TextField(blank=True, editable=False, max_length=512, null=True),
        ),
    ]
