# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0010_auto_20160613_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='pid',
            field=models.IntegerField(editable=False),
        ),
    ]
