# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-27 02:32
from __future__ import unicode_literals

import borg_utils.resource_status
import borg_utils.transaction
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablemanager', '0037_auto_20170607_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'The name of wms layer', max_length=128)),
                ('crs', models.CharField(editable=False, max_length=64, null=True)),
                ('bbox', models.CharField(editable=False, max_length=128, null=True)),
                ('kmi_bbox', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(editable=False, max_length=512, null=True)),
                ('abstract', models.TextField(editable=False, null=True)),
                ('kmi_name', models.SlugField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile(b'^[a-zA-Z0-9_\\-]+$'), b'Slug can only start with letters or underscore, and contain letters, numbers and underscore', b'invalid')])),
                ('path', models.CharField(editable=False, max_length=512, null=True)),
                ('legend', models.CharField(editable=False, max_length=512, null=True)),
                ('applications', models.TextField(blank=True, editable=False, null=True)),
                ('geoserver_setting', models.TextField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[(b'New', b'New'), (b'Updated', b'Updated'), (b'Published', b'Published'), (b'CascadePublished', b'CascadePublished'), (b'Unpublished', b'Unpublished'), (b'CascadeUnpublished', b'CascadeUnpublished')], editable=False, max_length=32)),
                ('last_publish_time', models.DateTimeField(editable=False, null=True)),
                ('last_unpublish_time', models.DateTimeField(editable=False, null=True)),
                ('last_refresh_time', models.DateTimeField(editable=False)),
                ('last_modify_time', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'ordering': ('server', 'name'),
            },
            bases=(models.Model, borg_utils.resource_status.ResourceStatusMixin, borg_utils.transaction.TransactionMixin),
        ),
        migrations.CreateModel(
            name='WmsServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text=b'The name of wms server', max_length=64, unique=True, validators=[django.core.validators.RegexValidator(re.compile(b'^[a-zA-Z0-9_\\-]+$'), b'Slug can only start with letters or underscore, and contain letters, numbers and underscore', b'invalid')])),
                ('capability_url', models.CharField(max_length=256)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('geoserver_setting', models.TextField(blank=True, editable=False, null=True)),
                ('layers', models.PositiveIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[(b'New', b'New'), (b'Updated', b'Updated'), (b'Published', b'Published'), (b'CascadePublished', b'CascadePublished'), (b'Unpublished', b'Unpublished'), (b'CascadeUnpublished', b'CascadeUnpublished')], editable=False, max_length=32)),
                ('last_refresh_time', models.DateTimeField(editable=False, null=True)),
                ('last_publish_time', models.DateTimeField(editable=False, null=True)),
                ('last_unpublish_time', models.DateTimeField(editable=False, null=True)),
                ('last_modify_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablemanager.Workspace')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model, borg_utils.resource_status.ResourceStatusMixin, borg_utils.transaction.TransactionMixin),
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='server',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wmsmanager.WmsServer'),
        ),
        migrations.CreateModel(
            name='InterestedWmsLayer',
            fields=[
            ],
            options={
                'verbose_name': 'Wms layer (Interested)',
                'proxy': True,
                'verbose_name_plural': 'Wms layers (Interested)',
            },
            bases=('wmsmanager.wmslayer',),
        ),
        migrations.CreateModel(
            name='PublishedWmsLayer',
            fields=[
            ],
            options={
                'verbose_name': 'Wms layer (Published)',
                'proxy': True,
                'verbose_name_plural': 'Wms layers (Published)',
            },
            bases=('wmsmanager.wmslayer',),
        ),
        migrations.AlterUniqueTogether(
            name='wmslayer',
            unique_together=set([('server', 'name'), ('server', 'kmi_name')]),
        ),
    ]
