# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmsmanager', '0009_auto_20160629_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wmslayer',
            name='kmi_abstract',
        ),
        migrations.RemoveField(
            model_name='wmslayer',
            name='kmi_title',
        ),
    ]
