# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 02:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('wmsmanager', '0010_auto_20160629_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslayer',
            name='legend',
            field=models.CharField(editable=False, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='wmslayer',
            name='kmi_name',
            field=models.SlugField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile(b'^[a-zA-Z_][a-zA-Z0-9_]+$'), b'Slug can only start with letters or underscore, and contain letters, numbers and underscore', b'invalid')]),
        ),
        migrations.AlterField(
            model_name='wmsserver',
            name='name',
            field=models.SlugField(help_text=b'The name of wms server', max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile(b'^[a-zA-Z_][a-zA-Z0-9_]+$'), b'Slug can only start with letters or underscore, and contain letters, numbers and underscore', b'invalid')]),
        ),
    ]
