# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-20 01:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('wmsmanager', '0011_auto_20161202_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmslayer',
            name='kmi_name',
            field=models.SlugField(max_length=128, validators=[django.core.validators.RegexValidator(re.compile(b'^[a-zA-Z0-9_\\-]+$'), b'Slug can only start with letters or underscore, and contain letters, numbers and underscore', b'invalid')]),
        ),
        migrations.AlterField(
            model_name='wmsserver',
            name='name',
            field=models.SlugField(help_text=b'The name of wms server', max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile(b'^[a-zA-Z0-9_\\-]+$'), b'Slug can only start with letters or underscore, and contain letters, numbers and underscore', b'invalid')]),
        ),
    ]
