# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-18 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsmanager', '0012_auto_20170420_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslayer',
            name='kmi_bbox',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
