# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-26 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsmanager', '0013_wmslayer_kmi_bbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmslayer',
            name='server',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
