# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-26 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmsmanager', '0015_auto_20180226_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wmslayer',
            options={'ordering': ('server_name', 'name')},
        ),
        migrations.RenameField(
            model_name='wmslayer',
            old_name='server',
            new_name='server_name',
        ),
        migrations.AlterUniqueTogether(
            name='wmslayer',
            unique_together=set([('server_name', 'kmi_name'), ('server_name', 'name')]),
        ),
    ]
