# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-26 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmsmanager', '0016_auto_20180226_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslayer',
            name='server',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='wmsmanager.WmsServer'),
            preserve_default=False,
        ),
    ]
