# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-26 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmsmanager', '0017_wmslayer_server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wmslayer',
            options={'ordering': ('server', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='wmslayer',
            unique_together=set([('server', 'name'), ('server', 'kmi_name')]),
        ),
    ]
