# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-26 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmsmanager', '0018_auto_20180226_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wmslayer',
            name='server_name',
        ),
    ]
